#!/usr/bin/env perl

use warnings;
use strict;

use 5.022;

BEGIN {push @INC, '.'}

use File::Slurp::Tiny qw/ read_file /;
use Report::Generator;

my $collection_name = shift @ARGV;
my $target = shift @ARGV;

my $report = Report::Generator->new(title => "QC Report for $collection_name");

for (@ARGV) {
    $report->append(read_file($_));
}

open (my $tex, '>', $target) or die("Failed to open $target for writing: $!");
print $tex $report->to_string;
close $tex;

